### ISSUE TITLE
long username pushes following box to right

### ISSUE THREAD

**Issue by karencarrens** [busyorg/busy#911] opened 2017-10-27 19:39 UTC
#### Actual behavior

long username pushes following box to right.

![long user name pushes box to right](https://user-images.githubusercontent.com/32652555/32122002-7f1f0692-bb24-11e7-9c6d-90a8f65200e4.JPG)

#### How to reproduce

* Browser: chrome
* Operating system: win 10

**Comment by espoem** [comment] 2017-10-27 19:46
You have to look at the previously reported issues. This is duplicate #840

**Comment by Sekhmet** [comment] 2017-10-29 12:27
Duplicate of #840

**Closed by Sekhmet** 2017-10-29 12:27 UTC
