### ISSUE TITLE
In editor input video link adds extra comma with every letter and space.

### ISSUE THREAD

**Issue by ashiqurakash** [busyorg/busy#1976] opened 2018-06-17 22:28 UTC
#### Expected behavior
In editor input writing something besides a video link in the same line must not add commas after every letter and in every space user use. 

#### Actual behavior
After writing something besides a video link in the editor input causes adding extra commas with every letter and space. 

#### How to reproduce
1. To reproduce this bug go to busy.org
2. Go to create new post or in the comment section.
3. Then write something in the editor input box.
4. Copy a video link and paste it besides the writing. 
5. Note that you will find the bug that after pasting the video link adds an extra comma with every letter and space of the same line. For better understanding please watch the video. 
#### Recorded video
https://vimeo.com/275530199
* Browser: Google Chrome Version 67.0.3396.87 (Official Build) (64-bit)
* Operating system: Windows 10 Pro

**Comment by Sekhmet** [comment] 2018-06-18 07:19
Duplicate of #1966

**Closed by Sekhmet** 2018-06-18 07:19 UTC
