### ISSUE TITLE
Error in payout calculation time

### ISSUE THREAD

**Issue by gregory-latinier** [busyorg/busy#1091] opened 2017-11-17 15:54 UTC
#### Expected behavior

Correct payout time remaining should be displayed

#### Actual behavior
![image](https://user-images.githubusercontent.com/13222767/32955941-bdd0ded0-cbb7-11e7-9291-712670ddeaee.png)

![image](https://user-images.githubusercontent.com/13222767/32955953-c696177e-cbb7-11e7-96ef-6d84a0c22f9a.png)

You can see there is a one hour delay.

#### How to reproduce

Hover payout in steemit and busy an hour before the real payout occurs

**Comment by Sekhmet** [comment] 2017-11-20 15:15
Duplicate of #1062

**Closed by Sekhmet** 2017-11-20 15:15 UTC
Labels: type: Bug
