### ISSUE TITLE
Follow a user from his profile Page will not update the followers count/list without refreshing

### ISSUE THREAD

**Issue by mynameisek** [busyorg/busy#498] opened 2017-05-21 11:40 UTC
When you follow a user from his profile page, you see Followers count, but it does not update live, as well as followers list
![followerlive](https://cloud.githubusercontent.com/assets/8390894/26283535/f4f1b3a0-3e2a-11e7-9b44-c325ae85c4db.gif)

**Comment by mynameisek** [comment] 2017-05-23 15:26
Follow/Unfollow from the list should also update instantaneously

**Comment by Sekhmet** [comment] 2017-11-03 22:22
This issue was related to Busy v1. Now we have duplicate of this issue #896.
I would close this one as it was related to Busy v1.

**Closed by Sekhmet** 2017-11-03 22:22 UTC
