### ISSUE TITLE
Busy - Incorrect rendering of page

### ISSUE THREAD

**Issue by MWFIAE** [busyorg/busy#1577] opened 2018-02-27 16:57 UTC
## Expected behavior
Content on [busy.org](https://busy.org) should be rendered exactly like it is on other frontends [steemit](https://steemit.com) or [utopian.io](https://utopian.io) for example.

## Actual behavior
This [post](https://busy.org/@aliyu-s/how-to-create-responsive-and-customizable-charts-using-chartist-js) is beeing displayed in the wrong way on busy, while it is rendering just fine in [utopian](https://utopian.io/utopian-io/@aliyu-s/how-to-create-responsive-and-customizable-charts-using-chartist-js) or [steemit](https://steemit.com/@aliyu-s/how-to-create-responsive-and-customizable-charts-using-chartist-js). Other postson busy render just fine for me. 

## How to reproduce
Just load this site: https://busy.org/@aliyu-s/how-to-create-responsive-and-customizable-charts-using-chartist-js

Operating system: Win10

Tested with following Browsers:
* latest Chrome Version 63.0.3239.132 (Offizieller Build) (64-Bit)
* Internet Explorer 11.192.16299.0
* Microsoft Edge

## Recording Of The Bug
As you can see the site is completly broken and unreadable for me after scrolling down a bit.
![image.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1519727162/hesqptkjakehg5voqswa.png)

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@mwfiae/busy-incorrect-rendering-of-page">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by damaera** [comment] 2018-03-09 04:17
is this already fixed?
I cannot reproduce this

OS: deepin
browser: chrome 63

**Comment by Sekhmet** [comment] 2018-04-11 21:31
Fixed in #1688

**Closed by Sekhmet** 2018-04-11 21:31 UTC
Labels: Bug
