### ISSUE TITLE
Wallet history loads 2 items, then repeatedly calls steem api

### ISSUE THREAD

**Issue by kirkins** [busyorg/busy#1702] opened 2018-04-03 21:38 UTC
I'm not exactly sure what causes this issue, but you can see it with [this user's wallet](https://busy.org/@maddmery/transfers).

I tried to fix it and I can see what function is getting called over and over. Not sure why it happens. Here is the function I logged on top of console results:

![all](https://user-images.githubusercontent.com/9503662/38277240-b8f4a3c8-3765-11e8-8882-7fc1376d44ca.png)

**Comment by kirkins** [comment] 2018-04-03 21:54
it stopped, maybe it was a local issue.

**Comment by Sekhmet** [comment] 2018-04-11 14:36
The problem is that recently api.steemit.com limited account history to 30 past days.
It doesn't signal it in any way, so there is no simple way of telling that we reached the end of history.

One solution might be to check if we received two responses with same `actionCount`, but it might be possible, that it can cause false positives (it might be possible that two responses have same `actionCount`, but there is more of a history for that user.

**Comment by Sekhmet** [comment] 2018-04-29 06:06
It should be fixed on staging.busy.org.

**Closed by Sekhmet** 2018-04-29 06:06 UTC
Labels: Bug, Difficulty: Medium
