### ISSUE TITLE
Discussion is displayed but the Followers tab is highlighted in a profile

### ISSUE THREAD

**Issue by espoem** [busyorg/busy#890] opened 2017-10-23 18:53 UTC
#### Expected behavior

Discussion should be displayed and highlighted when a profile is clicked.

#### Actual behavior

If you click on followers list and then want to display another profile, the discussion is displayed but the followers tab is highlighted.

<img src="https://user-images.githubusercontent.com/16621517/31907071-0b5022bc-b833-11e7-9f0c-38c9df5c9bfe.gif" height="280px"/>

<img src="https://user-images.githubusercontent.com/16621517/31907096-20204816-b833-11e7-862f-63613d02d748.png" height="280px"/>

#### How to reproduce

1. Go to any profile
2. Click on __Followers__
3. Go to another profile
4. Discussion is displayed but the followers tab is highlighted

* Browser: Chrome
* Operating system: Windows 10
* Reported by: `/utopian-io/@coffeenut/bug-report-for-busy-beta-visual-error-in-profile-page`

**Comment by sirrius-a-b** [comment] 2017-11-04 23:07
I cannot reproduce this bug on Chrome/Linux Mint. It might have been fixed in the mean time. Can anyone else confirm?

**Comment by Sekhmet** [comment] 2017-12-08 19:46
It works properly now.

**Closed by Sekhmet** 2017-12-08 19:46 UTC
Labels: Bug
