### ISSUE TITLE
Wrong estimated account value.

### ISSUE THREAD

**Issue by AneilPatel05** [busyorg/busy#1954] opened 2018-06-08 07:39 UTC
#### Expected behavior

Estimated account value should be calculated as per current Steem and SBD price.

#### Actual behavior

Estimated account value is way too higher than expected.

#### How to reproduce

* Browser: all
* Operating system: all

**Comment by bonustrack** [comment] 2018-06-11 07:17
Duplicate of #1948

**Closed by bonustrack** 2018-06-11 07:17 UTC
Labels: bug, priority: high
