### ISSUE TITLE
Scrolling through the messaging contact list

### ISSUE THREAD

**Issue by faddat** [busyorg/busy#301] opened 2017-02-02 03:34 UTC
Hey guys, I wasn't able to scroll through the contacts on the left-hand side.  Search worked fine :).

**Comment by tibonova** [comment] 2017-02-04 10:25
It's scrollable but only until the 20th name in the list. 

[![chat-scroll68560.png](http://www.steemimg.com/images/2017/02/04/chat-scroll68560.png)](http://www.steemimg.com/image/sdYa6)

I think the problem is that it uses similar code to the channels list (I'm guessing, haven't looked the code itself), where you added a `See more` link, but that is missing here.

**Comment by faddat** [comment] 2017-02-06 18:27
What is the API like?  Can you show me the JSON for sent messages?  I'm viewing this as an opportunity to test out a chain concept I have.....

**Comment by bonustrack** [comment] 2017-10-13 20:50
The chat has been depreciated in `new-design` i'm closing this issue.

**Closed by bonustrack** 2017-10-13 20:50 UTC
