### ISSUE TITLE
Bug : preview with youtube link

### ISSUE THREAD

**Issue by Deadz** [busyorg/busy#1966] opened 2018-06-12 15:04 UTC
#### Actual behavior

When I comment and I want to post a youtube link like : 

![msg](https://user-images.githubusercontent.com/21110315/41298407-96f11224-6e61-11e8-8205-af96eafd7316.jpg)

I have commas all over the place.

![preview](https://user-images.githubusercontent.com/21110315/41298505-cd192580-6e61-11e8-9aa9-fcc71c1b0585.jpg)

#### How to reproduce

You can past "texte texte texte https://www.youtube.com/watch?v=-FlxM_0S2lA texte texte texte" on the editor.

If you skip a line before and after the link, there is no problem

* Browser: Chrome 67.0.3396.79
* Operating system: Win 10

**Comment by Sekhmet** [comment] 2018-06-20 16:00
Duplicate of #1780

**Closed by Sekhmet** 2018-06-20 16:00 UTC
Labels: bug

**Comment by dhimmel** [comment] 2018-07-11 15:04
I'm also seeing this issue ([information here](https://busy.org/@dhimmel/re-advanticle-re-dhimmel-2018711t12324311z-20180711t031449684z/#comments)) where a [comment](https://busy.org/youtube/@advanticle/youtube-in-the-sh1t-over-bitconnect-promotion-ca5165326ec72#@advanticle/re-dhimmel-2018710t18120137z) appears like:

> ![](https://ipfs.busy.org/ipfs/QmNeCj7ofxmgjW7pkLxPAdesAsj7HLX8XpjN1y9hy4iJHD)
