### ISSUE TITLE
Bug : Wrong Steem Dollars Prices On Busy.org

### ISSUE THREAD

**Issue by walid321** [busyorg/busy#1950] opened 2018-06-06 10:09 UTC
#### Expected behavior

Busy.org should be show  correct stem dollars prices on market price.

#### Actual behavior

Busy.org is showing wrong steem dollars prices.
Which prices are not matched  with current steem dollars market prices.

#### How to reproduce

- Open a browser and go on https://busy.org/

- Log in your steemit account through steemconnect on busy.org

- Then click on **Wallet** 

- You can see it will showing wrong steem dollars prices.

- You can check steem dollars prices from other websites.

#### Recording Of The Bug
https://youtu.be/NAsAyDAZAxw

* Browser:  Google Chrome
Version 67.0.3396.62 (Official Build) beta (32-bit)

* Operating system: Windows 10

**Comment by itharagaian** [comment] 2018-06-08 04:49
See issue #1948

**Comment by bonustrack** [comment] 2018-06-11 07:18
Duplicate of #1948 i'm closing this issue

**Closed by bonustrack** 2018-06-11 07:18 UTC

**Comment by walid321** [comment] 2018-06-11 07:42
@bonustrack it's not a duplicate issue. When I published this issue, I didn't find any similar issue about this topic. you can check publish time then you will understand.

**Comment by bonustrack** [comment] 2018-06-11 07:50
You been reporting this issue in almost same time than @itharagaian. But as far as i can see there are both exactly the same issues, and #1948 came before #1950.
