### ISSUE TITLE
Content is not updated

### ISSUE THREAD

**Issue by kekkyojin** [busyorg/busy#1529] opened 2018-02-14 21:48 UTC
#### Expected behavior

After navigating on the website -opening profile or visiting some categories-, new content should be shown.

#### Actual behavior

Clicking in any tab is showing always the last shown content.

#### How to reproduce

Open busy.org. Look at the content. Go to your wallet (also see issue #1174, it is the same as this one, but this is more generic) or your profile or some category, it doesn't matter.

If you do some transfer, the balance will not appear as updated, even navigating and coming back to the wallet.

Wait for some time for your followers to publish new content.

Navigate again to your main page. You will see the last shown content. After refreshing the browser then every new post will be shown now.

* Browser: Tested in Firefox 58 and Opera 51
* Operating system:  macOS 10.13.3

**Comment by Sekhmet** [comment] 2018-03-05 21:30
Duplicate of #1406

**Closed by Sekhmet** 2018-03-05 21:30 UTC

**Comment by kekkyojin** [comment] 2018-03-07 11:57
Yes, sorry, it seems to be duplicate of that bug. I didn't search deep enough.
