### ISSUE TITLE
Changing Language is breaking layout [Interesting People Section]

### ISSUE THREAD

**Issue by Tanvir-rahman** [busyorg/busy#947] opened 2017-10-30 06:02 UTC
#### Expected behavior
After Language change from settings, All layout should be same.

#### Actual behavior

If I change the language, "Interesting people" Layout is breaking.
![1](https://user-images.githubusercontent.com/15964566/32156794-aeda5b74-bd69-11e7-9d5f-542d78847ee3.PNG)
![2](https://user-images.githubusercontent.com/15964566/32156795-af18eca4-bd69-11e7-8fbc-4983a7af4559.PNG)

#### How to reproduce

1) Go to https://nd.busy.org/
2) Select other language like Ex: "Bengali"
3) Click on Save

**Comment by espoem** [comment] 2017-10-30 06:37
This is duplicate of #840

**Closed** 2017-10-30 07:02 UTC
