### ISSUE TITLE
inconsistent reputation

### ISSUE THREAD

**Issue by economicstudio** [busyorg/busy#2152] opened 2019-01-16 23:28 UTC
#### Expected behavior

The reputations in the user info and post of the same user should be the same.

#### Actual behavior

The reputations in the user info and post of the same user are different.

#### How to reproduce

This occurs for most users, and the difference is noticeable for relatively low reputation users since normalized rep can be more different.

* Browser: any
* Operating system: any

#### Cause
This is due to the deprecated API `get_state` explained here:

> If any apps are still relying on get_state, we highly recommend ceasing use as soon as possible.
> https://steemit.com/steemit/@steemitdev/upcoming-changes-to-api-steemit-com

**Comment by Sekhmet** [comment] 2019-01-22 09:20
Can you provide a post/user that shows this problem?

**Comment by economicstudio** [comment] 2019-01-22 14:48
Sorry that I forgot to include the details, but it actually happens to most accounts including mine :), as shown below.

![](https://ipfs.busy.org/ipfs/QmR9cv1yf6ZP5rdzgNC7zt1Ld92TbmsbUdKppfFeU7pbR1)
> User info says it's 65.024

<br>

![](https://ipfs.busy.org/ipfs/QmY1jt6RDKGqaQgY7QFSDRLBsVHAnduWeL7F9NeF9XD9UE)
> But, post says it's 65.019

While they have changed now, but still they're different. As I mentioned, it's usually more noticeable for lower reputation accounts.

ps. could you comments on #2147 again? If you prefer 3 line, I'll do that.
And how do I know which version is currently deployed on busy.org?  thanks!

**Comment by Sekhmet** [comment] 2019-01-22 15:13
`develop` branch is deployed at https://staging.busy.org
`master` branch is deployed at https://busy.org

**Comment by Sekhmet** [comment] 2019-01-22 15:32
This problem isn't caused by `get_state`. We use `get_accounts` to get reputation on profile page, and `get_discussions_by_blog` (or similar methods) to get feed contents. Those two methods yield slightly different results.

For my account there is slight difference:
```
get_account: 1353498428522
get_discussions_by_blog: 1352418525462
```
I don't think there is anything we can do about it. Seems to be a problem with the API itself.

```bash
curl --request POST \
  --url https://api.steemit.com/ \
  --header 'content-type: text/plain;charset=UTF-8' \
  --header 'dnt: 1' \
  --header 'origin: https://busy.org' \
  --header 'referer: https://busy.org/@sekhmet' \
  --header 'user-agent: Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Mobile Safari/537.36' \
  --data '{"id":7,"jsonrpc":"2.0","method":"get_accounts","params":[["sekhmet"]]}'
```
```bash
curl --request POST \
  --url https://api.steemit.com/ \
  --header 'content-type: text/plain;charset=UTF-8' \
  --header 'dnt: 1' \
  --header 'origin: https://busy.org' \
  --header 'referer: https://busy.org/@sekhmet' \
  --header 'user-agent: Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Mobile Safari/537.36' \
  --data '{"id":11,"jsonrpc":"2.0","method":"get_discussions_by_blog","params":[{"tag":"sekhmet","limit":10}]}'
```

I will close this issue and hope that this issue will be resovled by the API at some point.

**Closed by Sekhmet** 2019-01-22 15:32 UTC

**Comment by economicstudio** [comment] 2019-01-23 11:01
@Sekhmet Thanks, but are you sure that `get_discussions_by_blog` is used for blog? To me https://github.com/busyorg/busy/blob/1611e3c289eaf4c33f5f178057df04405bf112d4/src/client/components/Sidebar/PostRecommendation.js#L59 is the only place where it is used. And this seems only for PostRecommendation.

In general, I agree with you. This problem is due to steem API. Thanks.
