### ISSUE TITLE
Issue when mass following on Busy

### ISSUE THREAD

**Issue by 1000goalgaming** [busyorg/busy#1478] opened 2018-02-05 15:11 UTC
#### Expected behavior

Similar to vanilla Steemit, bulk actions shouldn't be that much of a problem. Got 20 people to follow? Do it smoothly.

#### Actual behavior

Lag gets VERY intensive with every action you do, increasing more and more as you continue. Bulk actions basically become impossible on Busy.org. 

The issue is still rampant, I see freezes and jitters every once in a while. Sometimes I'll follow and then scroll, and then it will click people I didn't click and unfollow them. It causes a *lot* of unneeded stress.
#### How to reproduce

Perform 3+ actions at once, more for greater effect. Following is NOTORIOUS for this problem (try following a few people at once!)
* Browser: Chrome
* Operating system: Windows NT 10.1

**Comment by 1000goalgaming** [comment] 2018-02-05 15:11
Will post video when Steem bandwidth returns

**Comment by Sekhmet** [comment] 2018-02-05 15:27
Duplicate of #1351

**Closed by Sekhmet** 2018-02-05 15:27 UTC
