### ISSUE TITLE
Estimated upvote value is different than the actual value

### ISSUE THREAD

**Issue by espoem** [busyorg/busy#1173] opened 2017-12-09 17:44 UTC
I read a bug report for Utopian stating that estimated upvote value is different than the actual vote value that is displayed on the vote list. It was reported by deveerei and can be found in [Utopian GitHub repository](https://github.com/utopian-io/utopian.io/issues/196).

The same problem occurs on the staging site of busy. That is **staging.busy.org** and that may be actually the cause of the issue since Utopian use some features from Busy.

## Actual behaviour

If you want to upvote a post, you may have a slider enabled. For the simplicity, make a 100% vote and watch the estimated amount. After that, you can see the actual votes given on the list.

![vote-value.gif](https://res.cloudinary.com/hpiynhbhq/image/upload/v1512756731/jyka9f2k9ejxvafbahpd.gif)

## Expected behaviour

The vote value displayed in a slider and in the vote list should be the same or at least there should not be that huge difference.

## Steps to reproduce

1. Open staging.busy.org
2. Have slider enabled and vote for a post with 100% vote
3. Check the vote value on the vote list

- Browser: Chrome
- Operating system: Windows 10

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@espoem/estimated-upvote-value-is-different-than-the-actual-value">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by espoem** [comment] 2017-12-09 19:24
Sorry, it is most probably duplicate of #1057

**Comment by bonustrack** [comment] 2017-12-09 21:43
I'm closing this issue because it's a duplicate of #1057

**Closed by bonustrack** 2017-12-09 21:43 UTC
