### ISSUE TITLE
Relative link doesn't work well

### ISSUE THREAD

**Issue by bonustrack** [busyorg/busy#2109] opened 2018-09-06 01:33 UTC
There is an issue on how the relative links are handled, in this article https://busy.org/steem/@timcliff/it-s-time-to-start-paying-attention-to-steem the link `/steem/@timcliff/it-s-time-to-start-paying-attention-to-steem`
points to: https://steem/@timcliff/it-s-time-to-start-paying-attention-to-steem
instead of: https://busy.org/steem/@timcliff/it-s-time-to-start-paying-attention-to-steem

Reported by @timcliff

**Comment by Sekhmet** [comment] 2018-09-06 07:58
Duplicate of #2105

**Closed by Sekhmet** 2018-09-06 07:58 UTC
Labels: bug
